name: bizd_tech_service
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  loading_animation_widget: ^1.2.1
  intl: 0.20.2
  image_picker: ^1.1.2
  dio: ^5.4.0
  flutter_secure_storage: ^8.1.0
  path: ^1.9.0
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  uuid: ^4.5.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_spinkit: ^5.2.1
  provider: ^6.1.5
  signature: ^6.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pdf: ^3.8.4
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.12.3
  crypto: ^3.0.6
  syncfusion_flutter_pdfviewer: ^30.1.41
  geolocator: ^14.0.2
  flutter_background_service: ^5.1.0
  # flutter_local_notifications: ^19.4.0
  vibration: ^3.1.3
  awesome_notifications: ^0.10.1
  audioplayers: ^6.5.0
  # sqflite: ^2.4.2
  # flutter_polyline_points: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - images/svg/key.svg
    - images/svg/building.svg
    - images/svg/contact.svg
    - images/svg/service.svg
    - images/svg/activity.svg
    - images/svg/material.svg
    - images/svg/tool.svg
    - images/svg/task_check.svg
    - images/svg/dolla.svg
    - images/svg/image.svg
    - images/svg/clock.svg
    - images/svg/signature.svg
    - images/svg/check_cicle.svg
    - images/svg/pic.svg
    - images/svg/schedule.svg
    - images/svg/report.svg
    - images/svg/barcode.svg
    - images/svg/barcode2.svg
    - images/svg/barcode3.svg
    - images/svg/database.svg
    - images/svg/desc.svg
    - images/logo.png
    - images/bg.png
    - images/svg/tol_vis_2.svg
    - images/svg/key.svg
    - images/svg/reply.svg
    - images/svg/setting.svg
    - images/svg/kjav_list.svg
    - images/svg/kjav3.svg
    - images/svg/scann_camera.svg
    - images/svg/images2.svg
    - images/svg/check-cycle.svg
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
